name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ikev2-vpn
  CR_PAT: '${{ secrets.CR_PAT }}'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
